services:
  database:
    image: 'postgres:13'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: url_shortener
    volumes:
      - ./dbdata:/var/lib/postgresql/data