package com.learning.urlshortener.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


/**
 *Link information.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Link {

    /**
     * Unique identifier.
     * Controller by database.
     */
    private Long id;

    /**
     * Generated by application unique six-character unique token for each provided {@link Link#url}.
     */
    private String token;

    /**
     * Provided by user url.
     */
    private String url;

    /**
     * Provides {@link Link#token} click count number.
     * Auto-incremented for each {@link Link#token} request.
     * Must be positive.
     */
    private Integer clickCount;

}
