package com.learning.urlshortener.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


/**
 *Link information.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Link {

    /**
     * Unique identifier.
     * Controller by database.
     */
    private Long id;

    /**
     * Generated by application url shortcut for each provided {@link Link#url}.
     * <p>
     * Consist of base domain followed by generated unique six-character key.
     * Example: "http://domain.com/dRt9u".
     * <p>
     * Process description: when user requests shortcut version, the application
     * checks database to find related link entity, and if its found
     * redirects user to the {@link Link#url}.
     */
    private String shortenedUrl;

    /**
     * Provided by user url.
     */
    private String url;

    /**
     * Provides {@link Link#shortenedUrl} click count number.
     * Auto-incremented for each {@link Link#shortenedUrl} request.
     * Must be positive.
     */
    private Integer clickCount;

}
